# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Lean
    command: |
      curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:nightly -y
      echo 'export PATH="$HOME/.elan/bin:$PATH"' >> $HOME/.bashrc
      export PATH="$HOME/.elan/bin:$PATH"
vscode:
  extensions:
    - leanprover.lean4