name: build and deploy docs

on:
  schedule:
    - cron: '0 */24 * * *' # every 24 hours
  workflow_dispatch:
jobs:
  build:
    name: build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: setup ssh keys
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.DOC_DEPLOY_KEY }}
      
      - name: generate docs
        run: python ci/build-and-deploy-docs.py
